# Generated by Django 4.1.7 on 2023-03-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userlocation",
            name="village",
        ),
        migrations.AddField(
            model_name="userlocation",
            name="Property_number",
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name="userlocation",
            name="age",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="userlocation",
            name="gender",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Male"), (2, "Female"), (3, "Others")], default=1
            ),
        ),
        migrations.AddField(
            model_name="userlocation",
            name="national_id",
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name="userlocation",
            name="phone_number",
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name="userlocation",
            name="profile_image",
            field=models.ImageField(default="icon.jpg", upload_to="profiles"),
        ),
        migrations.AddField(
            model_name="userlocation",
            name="second_number",
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name="userlocation",
            name="cell",
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name="userlocation",
            name="district",
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name="userlocation",
            name="province",
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name="userlocation",
            name="sector",
            field=models.CharField(default=1, max_length=200),
        ),
    ]
