# Generated by Django 4.1.7 on 2023-03-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0002_remove_userlocation_village_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Customer"), (2, "Employee"), (3, "Admin")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="userlocation",
            name="Property_number",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="userlocation",
            name="cell",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="userlocation",
            name="district",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="userlocation",
            name="national_id",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="userlocation",
            name="phone_number",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="userlocation",
            name="province",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="userlocation",
            name="second_number",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="userlocation",
            name="sector",
            field=models.CharField(default="", max_length=200),
        ),
    ]
