# Generated by Django 4.1.7 on 2023-03-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0003_alter_user_user_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userlocation",
            old_name="Property_number",
            new_name="property_number",
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    ("CUSTOMER", "Customer"),
                    ("EMPLOYEE", "Employee"),
                    ("ADMIN", "Admin"),
                ],
                default="CUSTOMER",
            ),
        ),
    ]
