# Generated by Django 4.1.7 on 2023-03-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0004_rename_property_number_userlocation_property_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("CUSTOMER", "Customer"),
                    ("EMPLOYEE", "Employee"),
                    ("ADMIN", "Admin"),
                ],
                default="CUSTOMER",
                max_length=200,
            ),
        ),
    ]
