# Generated by Django 4.1.7 on 2023-03-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0006_remove_userlocation_national_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userlocation",
            name="cell",
        ),
        migrations.RemoveField(
            model_name="userlocation",
            name="district",
        ),
        migrations.RemoveField(
            model_name="userlocation",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="userlocation",
            name="property_number",
        ),
        migrations.RemoveField(
            model_name="userlocation",
            name="province",
        ),
        migrations.RemoveField(
            model_name="userlocation",
            name="sector",
        ),
        migrations.RemoveField(
            model_name="userlocation",
            name="user",
        ),
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="user",
            name="cell",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="district",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Male"), (2, "Female"), (3, "Others")], default=1
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="property_number",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="province",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="sector",
            field=models.CharField(default="", max_length=200),
        ),
    ]
