# Generated by Django 4.1.7 on 2023-04-03 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0008_alter_user_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_otp_enabled", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="UserLocation",
        ),
        migrations.AddField(
            model_name="user",
            name="otp_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("Customer", "Customer"),
                    ("Employee", "Employee"),
                    ("Admin", "Admin"),
                ],
                default="CUSTOMER",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="otp",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
